name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
    
    - name: Run tests
      run: mvn -B test --file pom.xml
    
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests - Java ${{ matrix.java }}
        path: '**/surefire-reports/TEST-*.xml'
        reporter: java-junit

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: maven
    
    - name: Run SpotBugs
      run: mvn -B spotbugs:check --file pom.xml
      continue-on-error: true
    
    - name: Run Checkstyle
      run: mvn -B checkstyle:check --file pom.xml
      continue-on-error: true
    
    - name: Analyze with SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        if [ -n "$SONAR_TOKEN" ]; then
          mvn -B sonar:sonar \
            -Dsonar.projectKey=dataliquid_parent-oss \
            -Dsonar.organization=dataliquid \
            -Dsonar.host.url=https://sonarcloud.io
        fi
      continue-on-error: true