name: Gitflow Hotfix

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Gitflow action to perform'
        required: true
        type: choice
        options:
          - hotfix-start
          - hotfix-finish
      version:
        description: 'Hotfix version (e.g., 1.17.1)'
        required: true
        type: string

jobs:
  hotfix:
    uses: dataliquid/github-actions/.github/workflows/gitflow-hotfix.yml@main
    with:
      action: ${{ inputs.action }}
      version: ${{ inputs.version }}
      java-version: '8'
      java-distribution: 'temurin'